# GSkit specific definitions
# Used by various parts of the ICC build to build the correct binaries
# or to locate the built lib to link against it
# Note that this only means we link correctly - runtime is another
# problem.

#
# GSkit version we are building for
GSK_VER		=	8

# Where we park the binaries
GSK_DIR		=	$(ICC_ROOT)/package/gskit_crypto

$(GSK_DIR):
	$(MKDIR) $@

# Where we find the header files for using GSkit-crypto
GSK_SDK		=	$(ICC_ROOT)/package/gsk_sdk

$(GSK_SDK):
	$(MKDIR) $@

# static lib must be seperate from the shared lib
$(GSK_SDK)/static: $(GSK_SDK)
	$(MKDIR) $@

# SDK headers

$(GSK_SDK)/icc.h: $(ICC_ROOT)/icc/icc.h $(GSK_SDK)
	$(CP) $< $@

$(GSK_SDK)/icc_a.h: $(ICC_ROOT)/iccpkg/iccpkg_a.h $(GSK_SDK)
	$(CP) $< $@

$(GSK_SDK)/iccglobals.h: $(ICC_ROOT)/icc/iccglobals.h $(GSK_SDK)
	$(CP) $< $@

#$(GSK_SDK)/iccversion.h: $(ICC_ROOT)/icc/iccversion.h $(GSK_SDK)
#	$(CP) $< $@


#
# Directories for Java version of GSkit_Crypto
#
JGSK_DIR		= $(ICC_ROOT)/package/jgskit_crypto
$(JGSK_DIR):
	$(MKDIR) $@

JGSK_SDK		= $(ICC_ROOT)/package/jgsk_sdk
$(JGSK_SDK):
	$(MKDIR) $@
$(JGSK_SDK)/docs: $(JGSK_SDK)
	$(MKDIR) $@
$(JGSK_SDK)/inc: $(JGSK_SDK)
	$(MKDIR) $@
$(JGSK_SDK)/bin: $(JGSK_SDK)
	$(MKDIR) $@
$(JGSK_SDK)/lib: $(JGSK_SDK)
	$(MKDIR) $@
$(JGSK_SDK)/debug: $(JGSK_SDK)
	$(MKDIR) $@

#
# Directories for ICKC_ namespaced version
#
ICKC_DIR = $(ICC_ROOT)/package/ickc_crypto
$(ICKC_DIR):
	$(MKDIR) $@

ICKC_SDK = $(ICC_ROOT)/package/ickc_sdk
$(ICKC_SDK):
	$(MKDIR) $@
$(ICKC_SDK)/docs: $(ICKC_SDK)
	$(MKDIR) $@
$(ICKC_SDK)/inc: $(ICKC_SDK)
	$(MKDIR) $@
$(ICKC_SDK)/bin: $(ICKC_SDK)
	$(MKDIR) $@
$(ICKC_SDK)/lib: $(ICKC_SDK)
	$(MKDIR) $@
$(ICKC_SDK)/debug: $(ICKC_SDK)
	$(MKDIR) $@


# Base library name
GSKLIB_ROOT = gsk$(GSK_VER)iccs
GSKLIB_B = $(SHLPRFX)$(GSKLIB_ROOT)
GSKLIB32 = $(GSKLIB_B)$(SHLSUFX)
GSKLIB64 = $(GSKLIB_B)_64$(SHLSUFX)
#GSKLIBS64 = $(GSKLIB_B)_s_64$(STLSUFX)
#GSKLIBI64 = $(GSKLIB_B)_64$(STLSUFX)
# JCEPlus variant
JGSKLIB_B = $(SHLPRFX)j$(GSKLIB_ROOT)
JGSKLIB32 = $(JGSKLIB_B)$(SHLSUFX)
JGSKLIB64 = $(JGSKLIB_B)_64$(SHLSUFX)
# ICKC variant
ICKCLIB_B = $(SHLPRFX)ickcs
ICKCLIB32 = $(ICKCLIB_B)$(SHLSUFX)
ICKCLIB64 = $(ICKCLIB_B)_64$(SHLSUFX)

# Where we find the link time dependencies.
# no "lib" prefix when -L is used - could just use lib full path like in windows
UNIX_ICCPKG_LIBS = -L$(GSK_DIR) -l$(GSKLIB_ROOT)
UNIX_ICCPKG_S_LIBS = -L$(GSK_SDK)/static -l$(GSKLIB_ROOT)
UNIX_GSK_LIB_STATIC = $(GSK_SDK)/static/$(GSKLIB_B)$(STLSUFX)
UNIX64_ICCPKG_LIBS = -L$(GSK_DIR) -l$(GSKLIB_ROOT)_64
UNIX64_ICCPKG_S_LIBS = -L$(GSK_SDK)/static -l$(GSKLIB_ROOT)_64
UNIX64_GSK_LIB_STATIC = $(GSK_SDK)/static/$(GSKLIB_B)_64$(STLSUFX)
# JCEPlus variant
UNIX_JCCPKG_LIBS = -L$(JGSK_DIR) -lj$(GSKLIB_ROOT)
UNIX64_JCCPKG_LIBS = -L$(JGSK_DIR) -lj$(GSKLIB_ROOT)_64
# ICKC variant
UNIX_ICKCPKG_LIBS = -L$(ICKC_DIR) -lickcs
UNIX64_ICKCPKG_LIBS = -L$(ICKC_DIR) -lickcs_64

#defaults to unix64 - need to override 32 bit and all WIN
$(OPSYS)_GSK_LIB_STATIC = $(UNIX64_GSK_LIB_STATIC)
$(OPSYS)_ICCPKG_S_LIBS = $(UNIX64_ICCPKG_S_LIBS)
$(OPSYS)_ICKCLIB = $(ICKCLIB64)
$(OPSYS)_ICKCPKG_LIBS = $(ICKC_SDK)/$(ICKCLIB_B)_64$(STLSUFX)

# Aux lib for linking
WIN_AUX_LIBS			= $(GSK_SDK)/iccaux$(VTAG).lib
UNIX_AUX_LIBS		   	= -L$(GSK_SDK) -liccaux$(VTAG)
UNIX64_AUX_LIBS			= -L$(GSK_SDK) -liccaux$(VTAG)

# default install loc
UNIX_GSK_GLOBAL         	= "/opt/ibm/gsk8/lib"
UNIX64_GSK_GLOBAL         	= "/opt/ibm/gsk8_64/lib64"
LINUX_GSK_GLOBAL        	= "/usr/local/ibm/gsk8/lib"
LINUX64_GSK_GLOBAL         	= "/usr/local/ibm/gsk8_64/lib64"

WIN_ICCPKG_LIBS = $(GSK_SDK)/$(GSKLIB_B).lib
WIN_JCCPKG_LIBS = $(JGSK_SDK)/lib/$(JGSKLIB_B).lib
WIN_ICKCPKG_LIBS = $(ICKC_SDK)/$(ICKCLIB_B).lib

WIN32_ICCPKG_LIBS = $(WIN_ICCPKG_LIBS)
WIN32_ICCPKG_S_LIBS = $(GSK_SDK)/static/$(GSKLIB_B)$(STLSUFX)
WIN32_GSK_LIB_STATIC = $(GSK_SDK)/static/$(GSKLIB_B)$(STLSUFX)
WIN32_GSKLIB = $(GSKLIB32)
WIN32_JGSKLIB = $(JGSKLIB32)
WIN32_JCCPKG_LIBS = $(WIN_JCCPKG_LIBS)
WIN32_ICKCLIB = $(ICKCLIB32)
WIN32_ICKCPKG_LIBS = $(WIN_ICKCPKG_LIBS)
# Cygwin
WIN32_GSK_SETUP = export PATH='$(GSK_DIR):$(PACKAGE_DIR):${PATH}'
WIN32_AUX_LIBS			= $(WIN_AUX_LIBS)

WIN32_VS2013_ICCPKG_LIBS = $(WIN_ICCPKG_LIBS)
WIN32_VS2013_ICCPKG_S_LIBS = $(WIN32_ICCPKG_S_LIBS)
WIN32_VS2013_GSK_LIB_STATIC = $(WIN32_GSK_LIB_STATIC)
WIN32_VS2013_GSKLIB = $(GSKLIB32)
WIN32_VS2013_JGSKLIB = $(JGSKLIB32)
WIN32_VS2013_JCCPKG_LIBS = $(WIN_JCCPKG_LIBS)
WIN32_VS2013_ICKCLIB = $(ICKCLIB32)
WIN32_VS2013_ICKCPKG_LIBS = $(WIN_ICKCPKG_LIBS)
# Cygwin
WIN32_VS2013_GSK_SETUP = export PATH='$(GSK_DIR):$(PACKAGE_DIR):${PATH}'
WIN32_VS2013_AUX_LIBS		= $(WIN_AUX_LIBS)

WIN32_VS2022_ICCPKG_LIBS = $(WIN_ICCPKG_LIBS)
WIN32_VS2022_ICCPKG_S_LIBS = $(WIN32_ICCPKG_S_LIBS)
WIN32_VS2022_GSK_LIB_STATIC = $(WIN32_GSK_LIB_STATIC)
WIN32_VS2022_GSKLIB = $(GSKLIB32)
WIN32_VS2022_JGSKLIB = $(JGSKLIB32)
WIN32_VS2022_JCCPKG_LIBS = $(WIN_JCCPKG_LIBS)
WIN32_VS2022_ICKCLIB = $(ICKCLIB32)
WIN32_VS2022_ICKCPKG_LIBS = $(WIN_ICKCPKG_LIBS)
WIN32_VS2022_GSK_SETUP = export PATH='$(GSK_DIR)'
WIN32_VS2022_AUX_LIBS		= $(WIN_AUX_LIBS)

WIN64_ICCPKG_LIBS = $(GSK_SDK)/$(GSKLIB_B)_64$(STLSUFX)
WIN64_ICCPKG_S_LIBS = $(GSK_SDK)/static/$(GSKLIB_B)_64$(STLSUFX)
WIN64_GSK_LIB_STATIC = $(GSK_SDK)/static/$(GSKLIB_B)_64$(STLSUFX)
WIN64_GSKLIB = $(GSKLIB64)
WIN64_JGSKLIB = $(JGSKLIB64)
WIN64_JCCPKG_LIBS = $(JGSK_SDK)/lib/$(JGSKLIB_B)_64$(STLSUFX)
WIN64_ICKCLIB = $(ICKCLIB64)
WIN64_ICKCPKG_LIBS = $(ICKC_SDK)/$(ICKCLIB_B)_64$(STLSUFX)
WIN64_GSK_SETUP			= $(WIN32_GSK_SETUP)
WIN64_AUX_LIBS			= $(WIN_AUX_LIBS)

WIN64_AMD_ICCPKG_LIBS = $(WIN64_ICCPKG_LIBS)
WIN64_AMD_ICCPKG_S_LIBS = $(WIN64_ICCPKG_S_LIBS)
WIN64_AMD_GSK_LIB_STATIC = $(WIN64_GSK_LIB_STATIC)
WIN64_AMD_GSKLIB = $(GSKLIB64)
WIN64_AMD_JGSKLIB = $(JGSKLIB64)
WIN64_AMD_JCCPKG_LIBS = $(WIN64_JCCPKG_LIBS)
WIN64_AMD_ICKCLIB = $(ICKCLIB64)
WIN64_AMD_ICKCPKG_LIBS = $(ICKC_SDK)/$(ICKCLIB_B)_64$(STLSUFX)
WIN64_AMD_GSK_SETUP		= $(WIN32_GSK_SETUP)
WIN64_AMD_AUX_LIBS		= $(WIN_AUX_LIBS)

WIN64_AMD_VS2013_ICCPKG_LIBS = $(WIN64_ICCPKG_LIBS)
WIN64_AMD_VS2013_ICCPKG_S_LIBS = $(WIN64_ICCPKG_S_LIBS)
WIN64_AMD_VS2013_GSK_LIB_STATIC = $(WIN64_GSK_LIB_STATIC)
WIN64_AMD_VS2013_GSKLIB = $(GSKLIB64)
WIN64_AMD_VS2013_JGSKLIB = $(JGSKLIB64)
WIN64_AMD_VS2013_JCCPKG_LIBS = $(WIN64_JCCPKG_LIBS)
WIN64_AMD_VS2013_ICKCLIB = $(ICKCLIB64)
WIN64_AMD_VS2013_ICKCPKG_LIBS = $(ICKC_SDK)/$(ICKCLIB_B)_64$(STLSUFX)
WIN64_AMD_VS2013_GSK_SETUP		= $(WIN32_GSK_SETUP)
WIN64_AMD_VS2013_AUX_LIBS		= $(WIN_AUX_LIBS)

WIN64_VS2022_ICCPKG_LIBS = $(WIN64_ICCPKG_LIBS)
WIN64_VS2022_ICCPKG_S_LIBS = $(WIN64_ICCPKG_S_LIBS)
WIN64_VS2022_GSK_LIB_STATIC = $(WIN64_GSK_LIB_STATIC)
WIN64_VS2022_GSKLIB = $(GSKLIB64)
WIN64_VS2022_JGSKLIB = $(JGSKLIB64)
WIN64_VS2022_JCCPKG_LIBS = $(WIN64_JCCPKG_LIBS)
WIN64_VS2022_ICKCLIB = $(ICKCLIB64)
WIN64_VS2022_ICKCPKG_LIBS = $(ICKC_SDK)/$(ICKCLIB_B)_64$(STLSUFX)
WIN64_VS2022_GSK_SETUP = $(WIN32_VS2022_GSK_SETUP)
WIN64_VS2022_AUX_LIBS		= $(WIN_AUX_LIBS)


LINUX_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
LINUX_ICCPKG_S_LIBS = $(UNIX_ICCPKG_S_LIBS)
LINUX_GSK_LIB_STATIC = $(UNIX_GSK_LIB_STATIC)
LINUX_GSKLIB			= $(GSKLIB32)
LINUX_JGSKLIB			= $(JGSKLIB32)
LINUX_JCCPKG_LIBS		= $(UNIX_JCCPKG_LIBS)
LINUX_ICKCLIB = $(ICKCLIB32)
LINUX_ICKCPKG_LIBS = $(UNIX_ICKCPKG_LIBS)
LINUX_GSK_SETUP = export LD_LIBRARY_PATH=$(GSK_DIR)
LINUX_AUX_LIBS			= $(UNIX_AUX_LIBS)

AMD64_LINUX_ICCPKG_LIBS		= $(UNIX64_ICCPKG_LIBS)
AMD64_LINUX_GSKLIB		= $(GSKLIB64)
AMD64_LINUX_JGSKLIB		= $(JGSKLIB64)
AMD64_LINUX_JCCPKG_LIBS		= $(UNIX64_JCCPKG_LIBS)
AMD64_LINUX_ICKCLIB = $(ICKCLIB64)
AMD64_LINUX_ICKCPKG_LIBS = $(UNIX64_ICKCPKG_LIBS)
AMD64_LINUX_GSK_GLOBAL     	= $(LINUX64_GSK_GLOBAL)
AMD64_LINUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
AMD64_LINUX_AUX_LIBS		= $(UNIX_AUX_LIBS)


ARM_LINUX_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
ARM_LINUX_ICCPKG_S_LIBS = $(UNIX_ICCPKG_S_LIBS)
ARM_LINUX_GSK_LIB_STATIC = $(UNIX_GSK_LIB_STATIC)
ARM_LINUX_GSKLIB		= $(GSKLIB32)
ARM_LINUX_JGSKLIB		= $(JGSKLIB32)
ARM_LINUX_JCCPKG_LIBS		= $(UNIX_JCCPKG_LIBS)
ARM_LINUX_ICKCLIB = $(ICKCLIB32)
ARM_LINUX_ICKCPKG_LIBS = $(UNIX_ICKCPKG_LIBS)
ARM_LINUX_GSK_GLOBAL     	= $(LINUX_GSK_GLOBAL)
ARM_LINUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
ARM_LINUX_AUX_LIBS		= $(UNIX_AUX_LIBS)

ARM64_LINUX_ICCPKG_LIBS		= $(UNIX64_ICCPKG_LIBS)
ARM64_LINUX_GSKLIB		= $(GSKLIB64)
ARM64_LINUX_JGSKLIB		= $(JGSKLIB64)
ARM64_LINUX_JCCPKG_LIBS		= $(UNIX64_JCCPKG_LIBS)
ARM64_LINUX_ICKCLIB = $(ICKCLIB64)
ARM64_LINUX_ICKCPKG_LIBS = $(UNIX64_ICKCPKG_LIBS)
ARM64_LINUX_GSK_GLOBAL     	= $(LINUX64_GSK_GLOBAL)
ARM64_LINUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
ARM64_LINUX_AUX_LIBS		= $(UNIX_AUX_LIBS)


PPC_LINUX_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
PPC_LINUX_ICCPKG_S_LIBS = $(UNIX_ICCPKG_S_LIBS)
PPC_LINUX_GSK_LIB_STATIC = $(UNIX_GSK_LIB_STATIC)
PPC_LINUX_GSKLIB		= $(GSKLIB32)
PPC_LINUX_JGSKLIB		= $(JGSKLIB32)
PPC_LINUX_JCCPKG_LIBS		= $(UNIX_JCCPKG_LIBS)
PPC_LINUX_ICKCLIB = $(ICKCLIB32)
PPC_LINUX_ICKCPKG_LIBS = $(UNIX_ICKCPKG_LIBS)
PPC_LINUX_GSK_GLOBAL       	= $(LINUX_GSK_GLOBAL)
PPC_LINUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
PPC_LINUX_AUX_LIBS		= $(UNIX_AUX_LIBS)

PPC64_LINUX_ICCPKG_LIBS		= $(UNIX64_ICCPKG_LIBS)
PPC64_LINUX_GSKLIB		= $(GSKLIB64)
PPC64_LINUX_JGSKLIB		= $(JGSKLIB64)
PPC64_LINUX_JCCPKG_LIBS		= $(UNIX64_JCCPKG_LIBS)
PPC64_LINUX_ICKCLIB = $(ICKCLIB64)
PPC64_LINUX_ICKCPKG_LIBS = $(UNIX64_ICKCPKG_LIBS)
PPC64_LINUX_GSK_GLOBAL       	= $(LINUX64_GSK_GLOBAL)
PPC64_LINUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
PPC64_LINUX_AUX_LIBS		= $(UNIX_AUX_LIBS)

PPC64LE_LINUX_ICCPKG_LIBS	= $(UNIX64_ICCPKG_LIBS)
PPC64LE_LINUX_GSKLIB		= $(GSKLIB64)
PPC64LE_LINUX_JGSKLIB		= $(JGSKLIB64)
PPC64LE_LINUX_JCCPKG_LIBS	= $(UNIX64_JCCPKG_LIBS)
PPC64LE_LINUX_ICKCLIB = $(ICKCLIB64)
PPC64LE_LINUX_ICKCPKG_LIBS = $(UNIX64_ICKCPKG_LIBS)
PPC64LE_LINUX_GSK_GLOBAL       	= $(LINUX64_GSK_GLOBAL)
PPC64LE_LINUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
PPC64LE_LINUX_AUX_LIBS		= $(UNIX_AUX_LIBS)

# May be obsolete (2025)
IA64_LINUX_ICCPKG_LIBS		= $(UNIX64_ICCPKG_LIBS)
IA64_LINUX_GSKLIB		= $(GSKLIB64)
IA64_LINUX_JGSKLIB		= $(JGSKLIB64)
IA64_LINUX_JCCPKG_LIBS		= $(UNIX64_JCCPKG_LIBS)
IA64_LINUX_ICKCLIB = $(ICKCLIB64)
IA64_LINUX_ICKCPKG_LIBS = $(UNIX64_ICKCPKG_LIBS)
IA64_LINUX_GSK_GLOBAL       	= $(LINUX64_GSK_GLOBAL)
IA64_LINUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
IA64_LINUX_AUX_LIBS		= $(UNIX_AUX_LIBS)


S390_LINUX_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
S390_LINUX_ICCPKG_S_LIBS = $(UNIX_ICCPKG_S_LIBS)
S390_LINUX_GSK_LIB_STATIC = $(UNIX_GSK_LIB_STATIC)
S390_LINUX_GSKLIB		= $(GSKLIB32)
S390_LINUX_JGSKLIB		= $(JGSKLIB32)
S390_LINUX_JCCPKG_LIBS		= $(UNIX_JCCPKG_LIBS)
S390_LINUX_ICKCLIB = $(ICKCLIB32)
S390_LINUX_ICKCPKG_LIBS = $(UNIX_ICKCPKG_LIBS)
S390_LINUX_GSK_GLOBAL		= $(LINUX_GSK_GLOBAL)
S390_LINUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
S390_LINUX_AUX_LIBS		= $(UNIX_AUX_LIBS)

S390X_LINUX_ICCPKG_LIBS		= $(UNIX64_ICCPKG_LIBS)
S390X_LINUX_GSKLIB		= $(GSKLIB64)
S390X_LINUX_JGSKLIB		= $(JGSKLIB64)
S390X_LINUX_JCCPKG_LIBS		= $(UNIX64_JCCPKG_LIBS)
S390X_LINUX_ICKCLIB = $(ICKCLIB64)
S390X_LINUX_ICKCPKG_LIBS = $(UNIX64_ICKCPKG_LIBS)
S390X_LINUX_GSK_GLOBAL		= $(LINUX64_GSK_GLOBAL)
S390X_LINUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
S390X_LINUX_AUX_LIBS		= $(UNIX_AUX_LIBS)


ZOS_ICCPKG_LIBS = $(GSK_SDK)/$(GSKLIB_B)_64.x $(ICC_ROOT)/icc/csvquery_64$(OBJSUFX)
ZOS_ICCPKG_S_LIBS = $(UNIX64_GSK_LIB_STATIC) $(ICC_ROOT)/icc/csvquery_64$(OBJSUFX)
ZOS_GSKLIB				= $(GSKLIB64)
ZOS_JGSKLIB				= $(JGSKLIB64)
ZOS_JCCPKG_LIBS = $(JGSK_SDK)/$(JGSKLIB_B)_64.x
ZOS_ICKCLIB = $(ICKCLIB64)
ZOS_ICKCPKG_LIBS = $(ICKC_SDK)/$(ICKCLIB_B)_64.x
ZOS_GSK_GLOBAL				= $(LINUX_GSK_GLOBAL)
ZOS_GSK_SETUP = export LIBPATH=$(GSK_DIR)
ZOS_AUX_LIBS				= $(UNIX_AUX_LIBS)

# ZOS ASCII mode
ZOSA_ICCPKG_LIBS = $(GSK_SDK)/$(GSKLIB_B)_64.x $(ICC_ROOT)/icc/csvquery_64$(OBJSUFX)
ZOSA_ICCPKG_S_LIBS = $(UNIX64_GSK_LIB_STATIC) $(ICC_ROOT)/icc/csvquery_64$(OBJSUFX)
ZOSA_GSKLIB				= $(GSKLIB64)
ZOSA_JGSKLIB				= $(JGSKLIB64)
ZOSA_JCCPKG_LIBS = $(JGSK_SDK)/$(JGSKLIB_B)_64.x
ZOSA_ICKCLIB = $(ICKCLIB64)
ZOSA_ICKCPKG_LIBS = $(ICKC_SDK)/$(ICKCLIB_B)_64.x
ZOSA_GSK_GLOBAL				= $(LINUX_GSK_GLOBAL)
ZOSA_GSK_SETUP = $(ZOS_GSK_SETUP)
ZOSA_AUX_LIBS				= $(UNIX_AUX_LIBS)

ZOS31_ICCPKG_LIBS = $(GSK_SDK)/$(GSKLIB_B).x $(ICC_ROOT)/icc/csvquery$(OBJSUFX)
ZOS31_ICCPKG_S_LIBS = $(UNIX_GSK_LIB_STATIC) $(ICC_ROOT)/icc/csvquery$(OBJSUFX)
ZOS31_GSK_LIB_STATIC = $(UNIX_GSK_LIB_STATIC)
ZOS31_GSKLIB				= $(GSKLIB32)
ZOS31_JGSKLIB				= $(JGSKLIB32)
ZOS31_JCCPKG_LIBS = $(JGSK_SDK)/$(JGSKLIB_B).x
ZOS31_ICKCLIB = $(ICKCLIB32)
ZOS31_ICKCPKG_LIBS = $(ICKC_SDK)/$(ICKCLIB_B).x
ZOS31_GSK_GLOBAL			= $(LINUX_GSK_GLOBAL)
ZOS31_GSK_SETUP = $(ZOS_GSK_SETUP)
ZOS31_AUX_LIBS				= $(UNIX_AUX_LIBS)

# ZOS 31 bit ASCII mode
ZOSA31_ICCPKG_LIBS = $(GSK_SDK)/$(GSKLIB_B).x $(ICC_ROOT)/icc/csvquery$(OBJSUFX)
ZOSA31_ICCPKG_S_LIBS = $(UNIX_GSK_LIB_STATIC) $(ICC_ROOT)/icc/csvquery$(OBJSUFX)
ZOSA31_GSK_LIB_STATIC = $(UNIX_GSK_LIB_STATIC)
ZOSA31_GSKLIB				= $(GSKLIB32)
ZOSA31_JGSKLIB				= $(JGSKLIB32)
ZOSA31_JCCPKG_LIBS = $(JGSK_SDK)/$(JGSKLIB_B).x
ZOSA31_ICKCLIB = $(ICKCLIB32)
ZOSA31_ICKCPKG_LIBS = $(ICKC_SDK)/$(ICKCLIB_B).x
ZOSA31_GSK_GLOBAL			= $(LINUX_GSK_GLOBAL)
ZOSA31_GSK_SETUP = $(ZOS_GSK_SETUP)
ZOSA31_AUX_LIBS				= $(UNIX_AUX_LIBS)


OSX_X86_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
OSX_X86_ICCPKG_S_LIBS = $(UNIX_ICCPKG_S_LIBS)
OSX_X86_GSK_LIB_STATIC = $(UNIX_GSK_LIB_STATIC)
OSX_X86_GSKLIB			= $(GSKLIB32)
OSX_X86_GSK_GLOBAL		= $(LINUX_GSK_GLOBAL)
OSX_X86_GSK_SETUP		= export DYLD_LIBRARY_PATH=$(GSK_DIR)
OSX_X86_AUX_LIBS		= $(UNIX_AUX_LIBS)

OSX_X86_64_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
OSX_X86_64_GSKLIB		= $(GSKLIB64)
OSX_X86_64_JGSKLIB = $(JGSKLIB64)
OSX_X86_64_JCCPKG_LIBS = $(UNIX_JCCPKG_LIBS)
OSX_X86_64_ICKCLIB = $(ICKCLIB64)
OSX_X86_64_ICKCPKG_LIBS = $(UNIX_ICKCPKG_LIBS)
OSX_X86_64_GSK_GLOBAL		= $(LINUX_GSK_GLOBAL)
OSX_X86_64_GSK_SETUP		= export DYLD_LIBRARY_PATH=$(GSK_DIR)
OSX_X86_64_AUX_LIBS		= $(UNIX_AUX_LIBS)

OSX_ARM64_ICCPKG_LIBS	= $(UNIX_ICCPKG_LIBS)
OSX_ARM64_ICCPKG_S_LIBS = $(UNIX_ICCPKG_S_LIBS)
OSX_ARM64_GSK_LIB_STATIC = $(UNIX_GSK_LIB_STATIC)
OSX_ARM64_GSKLIB		= $(GSKLIB32)
OSX_ARM64_JGSKLIB		= $(JGSKLIB32)
OSX_ARM64_JCCPKG_LIBS	= $(UNIX_JCCPKG_LIBS)
OSX_ARM64_ICKCLIB = $(ICKCLIB32)
OSX_ARM64_ICKCPKG_LIBS = $(UNIX_ICKCPKG_LIBS)
OSX_ARM64_GSK_GLOBAL	= $(LINUX_GSK_GLOBAL)
OSX_ARM64_GSK_SETUP	= export DYLD_LIBRARY_PATH=$(GSK_DIR)
OSX_ARM64_AUX_LIBS		= $(UNIX_AUX_LIBS)

OSXV9_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
OSXV9_ICCPKG_S_LIBS = $(UNIX_ICCPKG_S_LIBS)
OSXV9_GSK_LIB_STATIC = $(UNIX_GSK_LIB_STATIC)
OSXV9_GSKLIB			= $(GSKLIB32)
OSXV9_JGSKLIB			= $(JGSKLIB32)
OSXV9_JCCPKG_LIBS		= $(UNIX_JCCPKG_LIBS)
OSXV9_ICKCLIB = $(ICKCLIB32)
OSXV9_ICKCPKG_LIBS = $(UNIX_ICKCPKG_LIBS)
OSXV9_GSK_GLOBAL		= $(LINUX_GSK_GLOBAL)
OSXV9_GSK_SETUP		= export DYLD_LIBRARY_PATH=$(GSK_DIR)
OSXV9_AUX_LIBS		= $(UNIX_AUX_LIBS)


AIX_ICCPKG_LIBS			= -brtl $(UNIX_ICCPKG_LIBS)
AIX_ICCPKG_S_LIBS = $(UNIX_ICCPKG_S_LIBS)
AIX_GSK_LIB_STATIC = $(UNIX_GSK_LIB_STATIC)
AIX_GSKLIB			= $(GSKLIB32)
AIX_JGSKLIB			= $(JGSKLIB32)
AIX_JCCPKG_LIBS			= -brtl $(UNIX_JCCPKG_LIBS)
AIX_ICKCLIB = $(ICKCLIB32)
AIX_ICKCPKG_LIBS = -brtl $(UNIX_ICKCPKG_LIBS)
AIX_GSK_GLOBAL			= "/usr/opt/ibm/gsk8/lib"
AIX_GSK_SETUP			= export LIBPATH=$(GSK_DIR)
AIX_AUX_LIBS			= $(UNIX_AUX_LIBS)

AIX64_ICCPKG_LIBS		= -brtl $(UNIX64_ICCPKG_LIBS)
# static lib does not include old icc.o on this platform so try linking MUPPET instead
AIX64_ICCPKG_S_LIBS = $(MUPPET) $(UNIX64_ICCPKG_S_LIBS)
AIX64_GSKLIB			= $(GSKLIB64)
AIX64_JGSKLIB			= $(JGSKLIB64)
AIX64_JCCPKG_LIBS		= -brtl $(UNIX64_JCCPKG_LIBS)
AIX64_ICKCLIB = $(ICKCLIB64)
AIX64_ICKCPKG_LIBS = -brtl $(UNIX64_ICKCPKG_LIBS)
AIX64_GSK_GLOBAL		= "/usr/opt/ibm/gsk8_64/lib64"
AIX64_GSK_SETUP			= export LIBPATH=$(GSK_DIR)
AIX64_AUX_LIBS			= $(UNIX_AUX_LIBS)


SUN_ICCPKG_LIBS			= $(UNIX_ICCPKG_LIBS)
SUN_ICCPKG_S_LIBS = $(UNIX_ICCPKG_S_LIBS)
SUN_GSK_LIB_STATIC = $(UNIX_GSK_LIB_STATIC)
SUN_GSKLIB			= $(GSKLIB32)
SUN_JGSKLIB			= $(JGSKLIB32)
SUN_JCCPKG_LIBS			= $(UNIX_JCCPKG_LIBS)
SUN_ICKCLIB = $(ICKCLIB32)
SUN_ICKCPKG_LIBS = $(UNIX_ICKCPKG_LIBS)
SUN_GSK_GLOBAL			= $(UNIX_GSK_GLOBAL)
SUN_GSK_SETUP			= $(LINUX_GSK_SETUP)
SUN_AUX_LIBS			= $(UNIX_AUX_LIBS)

SUN64_ICCPKG_LIBS		= $(UNIX64_ICCPKG_LIBS)
SUN64_GSKLIB			= $(GSKLIB64)
SUN64_JGSKLIB			= $(JGSKLIB64)
SUN64_JCCPKG_LIBS		= $(UNIX64_JCCPKG_LIBS)
SUN64_ICKCLIB = $(ICKCLIB64)
SUN64_ICKCPKG_LIBS = $(UNIX64_ICKCPKG_LIBS)
SUN64_GSK_GLOBAL		= $(UNIX64_GSK_GLOBAL)
SUN64_GSK_SETUP			= $(SUN_GSK_SETUP)
SUN64_AUX_LIBS			= $(UNIX_AUX_LIBS)

SUN_AMD64_ICCPKG_LIBS		= $(UNIX64_ICCPKG_LIBS)
SUN_AMD64_GSKLIB		= $(GSKLIB64)
SUN_AMD64_JGSKLIB		= $(JGSKLIB64)
SUN_AMD64_JCCPKG_LIBS		= $(UNIX64_JCCPKG_LIBS)
SUN_AMD64_ICKCLIB = $(ICKCLIB64)
SUN_AMD64_ICKCPKG_LIBS = $(UNIX64_ICKCPKG_LIBS)
SUN_AMD64_GSK_GLOBAL		= $(SUN64_GSK_GLOBAL)
SUN_AMD64_GSK_SETUP		= $(SUN_GSK_SETUP)
SUN_AMD64_AUX_LIBS		= $(UNIX_AUX_LIBS)

SUN_X86_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
SUN_X86_ICCPKG_S_LIBS = $(UNIX_ICCPKG_S_LIBS)
SUN_X86_GSK_LIB_STATIC = $(UNIX_GSK_LIB_STATIC)
SUN_X86_GSKLIB			= $(GSKLIB32)
SUN_X86_JGSKLIB			= $(JGSKLIB32)
SUN_X86_JCCPKG_LIBS		= $(UNIX_JCCPKG_LIBS)
SUN_X86_ICKCLIB = $(ICKCLIB32)
SUN_X86_ICKCPKG_LIBS = $(UNIX_ICKCPKG_LIBS)
SUN_X86_GSK_GLOBAL		= $(SUN_GSK_GLOBAL)
SUN_X86_GSK_SETUP		= $(SUN_GSK_SETUP)
SUN_X86_AUX_LIBS		= $(UNIX_AUX_LIBS)


HPUX_ICCPKG_LIBS		= $(UNIX_ICCPKG_LIBS)
HPUX_ICCPKG_S_LIBS = $(UNIX_ICCPKG_S_LIBS)
HPUX_GSK_LIB_STATIC = $(UNIX_GSK_LIB_STATIC)
HPUX_GSKLIB			= $(GSKLIB32)
HPUX_JGSKLIB			= $(JGSKLIB32)
HPUX_JCCPKG_LIBS		= $(UNIX_JCCPKG_LIBS)
HPUX_ICKCLIB = $(ICKCLIB32)
HPUX_ICKCPKG_LIBS = $(UNIX_ICKCPKG_LIBS)
HPUX_GSK_GLOBAL			= $(UNIX_GSK_GLOBAL)
HPUX_GSK_SETUP			= $(LINUX_GSK_SETUP)
HPUX_AUX_LIBS			= $(UNIX_AUX_LIBS)

HPUX64_ICCPKG_LIBS		= $(UNIX64_ICCPKG_LIBS)
HPUX64_GSKLIB			= $(GSKLIB64)
HPUX64_JGSKLIB			= $(JGSKLIB64)
HPUX64_JCCPKG_LIBS		= $(UNIX64_JCCPKG_LIBS)
HPUX64_ICKCLIB = $(ICKCLIB64)
HPUX64_ICKCPKG_LIBS = $(UNIX64_ICKCPKG_LIBS)
HPUX64_GSK_GLOBAL		= $(UNIX64_GSK_GLOBAL)
HPUX64_GSK_SETUP		= $(LINUX_GSK_SETUP)
HPUX64_AUX_LIBS			= $(UNIX_AUX_LIBS)

IA64_HPUX_ICCPKG_LIBS = -L$(GSK_DIR) -l$(GSKLIB_ROOT)_32
IA64_HPUX_ICCPKG_S_LIBS = $(UNIX_ICCPKG_S_LIBS)
IA64_HPUX_GSK_LIB_STATIC = $(UNIX_GSK_LIB_STATIC)
IA64_HPUX_GSKLIB		= $(GSKLIB_B)_32$(SHLSUFX)
IA64_HPUX_JGSKLIB		= $(JGSKLIB_B)_32$(SHLSUFX)
IA64_HPUX_JCCPKG_LIBS = -L$(JGSK_DIR) -lj$(GSKLIB_ROOT)_32
IA64_HPUX_ICKCLIB = $(ICKCLIB_B)_32$(SHLSUFX)
IA64_HPUX_ICKCPKG_LIBS = -L$(ICKC_DIR) -lickcs_32
IA64_HPUX_GSK_GLOBAL		= $(HPUX_GSK_GLOBAL)
IA64_HPUX_GSK_SETUP		= $(LINUX_GSK_SETUP)
IA64_HPUX_AUX_LIBS		= $(UNIX_AUX_LIBS)

IA64_HPUX64_ICCPKG_LIBS		= $(UNIX64_ICCPKG_LIBS)
IA64_HPUX64_GSKLIB		= $(GSKLIB64)
IA64_HPUX64_JGSKLIB		= $(JGSKLIB64)
IA64_HPUX64_JCCPKG_LIBS		= $(UNIX64_JCCPKG_LIBS)
IA64_HPUX64_ICKCLIB = $(ICKCLIB64)
IA64_HPUX64_ICKCPKG_LIBS = $(UNIX64_ICKCPKG_LIBS)
IA64_HPUX64_GSK_GLOBAL		= $(HPUX64_GSK_GLOBAL)
IA64_HPUX64_GSK_SETUP		= $(LINUX_GSK_SETUP)
IA64_HPUX64_AUX_LIBS		= $(UNIX_AUX_LIBS)

# all the same for 64 bit
#$(OPSYS)_GSKLIBS = $(GSKLIBS64)

# Names of the GSkit-crypto libs for GSkit8
GSK_LIBNAME 			= $($(OPSYS)_GSKLIB)
GSK_LIB				= $(GSK_DIR)/$(GSK_LIBNAME)
#GSK_LIBNAME_S = $($(OPSYS)_GSKLIBS)
GSK_LIB_STATIC = $($(OPSYS)_GSK_LIB_STATIC)
#GSK_LIB_IMPORT = $(GSK_SDK)/import/$(GSKLIB_B)_64$(STLSUFX)
ICCPKG_S_LIBS = $($(OPSYS)_ICCPKG_S_LIBS)
ICCPKG_LIBS			= $($(OPSYS)_ICCPKG_LIBS)

# Names of the GSkit-Crypto libs for Java components
JGSK_LIBNAME 			= $($(OPSYS)_JGSKLIB)
JGSK_LIB			= $(JGSK_DIR)/$(JGSK_LIBNAME)
JCCPKG_LIBS			= $($(OPSYS)_JCCPKG_LIBS)

# Names of the GSkit-Crypto libs with ICKC_ namespace
ICKC_LIBNAME = $($(OPSYS)_ICKCLIB)
ICKC_LIB = $(ICKC_DIR)/$(ICKC_LIBNAME)
ICKCPKG_LIBS = $($(OPSYS)_ICKCPKG_LIBS)

# Global GSkit install dir
GSK_GLOBAL			= $($(OPSYS)_GSK_GLOBAL)

# LD_LIBRARY_PATH setup to find libs at runtume
GSK_SETUP			= $($(OPSYS)_GSK_SETUP)
# Link path to the aux library
AUX_LIBS			= $($(OPSYS)_AUX_LIBS)
