# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "ICC-Config-debug"
  # We can add more jobs here for different OS
  ICC-Config-debug:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: 64-bit Linux debug compile
        run: |
          cd icc
          make OPSYS=AMD64_LINUX CONFIG=debug create_all
          export LD_LIBRARY_PATH=/home/runner/work/OpenCryptographyKitC/OpenCryptographyKitC/openssl-1.1.1/
          make -k OPSYS=AMD64_LINUX CONFIG=debug all
          make -k OPSYS=AMD64_LINUX CONFIG=debug tests
          make -k OPSYS=AMD64_LINUX CONFIG=debug show_config
          cd ..

  ICC-Compile:
    # a compile only -no test -quick check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: 64-bit Linux release compile
        run: |
          cd icc
          make -k OPSYS=AMD64_LINUX CONFIG=release create_all
          export LD_LIBRARY_PATH=/home/runner/work/OpenCryptographyKitC/OpenCryptographyKitC/openssl-1.1.1/
          make -k OPSYS=AMD64_LINUX CONFIG=release all
          make -k OPSYS=AMD64_LINUX CONFIG=release iccpkg
          make -k OPSYS=AMD64_LINUX CONFIG=release show_config
          cd ..
          cd iccpkg
          make -k OPSYS=AMD64_LINUX CONFIG=release all
          cd ..

 
